name: Multi Job Pipeline

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Step
        run: echo "Building project..."

  test:
    runs-on: ubuntu-latest
    needs: build   # ðŸ‘ˆ This runs AFTER build
    steps:
      - uses: actions/checkout@v3
      - name: Test Step
        run: echo "Running tests..."

  deploy:
    runs-on: ubuntu-latest
    needs: test    # ðŸ‘ˆ This runs AFTER test
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Step
        run: echo "Deploying website..."
